services:
  mysql:
    image: mysql:8.0
    container_name: appointment_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    network_mode: host
    volumes:
      - appointment_db:/var/lib/mysql

volumes:
  appointment_db:
