services:
  postgres:
    image: postgres:16
    container_name: appointment_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    network_mode: host
    volumes:
      - appointment_db:/var/lib/postgresql/data

volumes:
  appointment_db:
